#!/usr/bin/env python3
"""Subscription client — connects to server.py, requests a topic, and streams events.

Architecture
------------
Each subscription is handled by :class:`~common.SecurePairClient`, an async
context manager that encapsulates the full lifecycle:

1. Sends a signed :class:`~common.SubscribeRequest` over a ``REQ`` socket.
2. Receives and verifies the server's signed :class:`~common.SubscribeResponse`.
3. Connects a ``PAIR`` socket to the address advertised by the server.
4. Performs the PAIR-level mutual Ed25519 auth + X25519 key exchange handshake.
5. Exposes encrypted :meth:`~common.SecurePairClient.arecv` /
   :meth:`~common.SecurePairClient.asend` methods for the application layer.

Multiple independent subscriptions can be run concurrently inside a
``TaskGroup`` — see the bottom of this file for a multi-topic example.

Usage
-----
    python client.py [--topics TOPIC [TOPIC ...]] [--transport tcp|ipc|inproc]
"""

import argparse
import asyncio
import json
import logging
import pathlib
from typing import override

import nacl.exceptions
import nacl.signing

import nng

from common import (
    DEFAULT_REP_URL,
    SubscribeRequest,
    SubscribeResponse
)
from secure_sockets.protocol_utils import (
    HANDSHAKE_TIMEOUT_S
)
from secure_sockets.secure_pair import (
    SecurePairClient,
)
from secure_sockets.secure_req import (
    SecureReqClient
)
from secure_sockets.security_utils import (
    b64dec,
    load_signing_key,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_HERE = pathlib.Path(__file__).parent

#: Path to the client's long-term Ed25519 signing key.
_CLIENT_KEY_PATH = _HERE / "keys" / "client_sign.key"

#: Hex-encoded Ed25519 verify key of the *legitimate* server.
#: Generated by gen_keys.py — paste the 'server' verify_key here.
SERVER_VERIFY_KEY = nacl.signing.VerifyKey(
    bytes.fromhex(
        "a9517420c135a993b6c91017717e362724c5a6d01b1b127282dfdbd03c74db57"
    )
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
_LOG = logging.getLogger("client")

# ----------------------------------------------------------------------------
# Private Pair socket
# ---------------------------------------------------------------------------



class EphemeralPairClient(SecurePairClient):
    """Client for the REP/REQ subscription protocol with post-handshake token.

    Mirrors :class:`EphemeralPairServer`:

    1. Dials the server's REP socket, sends a :class:`~common.SubscribeRequest`.
    2. Receives and verifies the :class:`~common.SubscribeResponse`
       (pair_addr + connection_token).
    3. Dials the PAIR socket and completes the mutual-auth handshake.
    4. Sends the connection token encrypted via the established connection

    Not thread-safe.
    """

    __slots__ = {
        "_connection_token": "Token received in SubscribeResponse; sent after PAIR handshake.",
        "_pair_addr": "NNG URL of the server's PAIR endpoint.",
    }

    _connection_token: bytes
    _pair_addr: str

    def __init__(
        self,
        pair_addr: str,
        connection_token: bytes,
        client_signing_key: nacl.signing.SigningKey,
        server_verify_key: nacl.signing.VerifyKey,
        *,
        timeout: float = HANDSHAKE_TIMEOUT_S,
    ) -> None:
        # pair_addr is unknown until negotiation; set to empty string as placeholder.
        super().__init__("", client_signing_key, server_verify_key, timeout=timeout)
        self._pair_addr = pair_addr
        self._connection_token = connection_token

    # ------------------------------------------------------------------
    # _connect / _aconnect
    # ------------------------------------------------------------------

    @override
    def _connect(self) -> None:
        """Complete the PAIR handshake, then send the connection token."""
        super()._connect()           # dials pair_addr, does PAIR handshake
        self.send(self._connection_token)  # encrypted via _box

    @override
    async def _aconnect(self) -> None:
        """Async version of _connect."""
        await super()._aconnect()           # dials pair_addr, does PAIR handshake
        await self.asend(self._connection_token)  # encrypted via _box


# ---------------------------------------------------------------------------
# Application: subscribe to one or more topics concurrently
# ---------------------------------------------------------------------------


async def stream_topic(
    response: SubscribeResponse,
    topic: str,
    max_events: int,
) -> None:
    """Subscribe to *topic* and print up to *max_events* events.

    Opens a :class:`~common.SecurePairClient` context for the full
    subscribe-handshake-stream lifecycle, then exits cleanly.

    Args:
        response: Subscription response from the server.
        topic: Topic identifier.
        max_events: Stop after receiving this many events (0 = run forever).
    """
    async with EphemeralPairClient(
        response.pair_addr,
        b64dec(response.connection_token_b64),
        client_signing_key=load_signing_key(_CLIENT_KEY_PATH),
        server_verify_key=SERVER_VERIFY_KEY
    ) as cli:
        count = 0
        while True:
            try:
                binary: bytes = await cli.arecv()
                event = json.dumps(binary.decode("utf-8"))
            except nng.NngClosed:
                _LOG.info("Server closed the feed for topic %r", topic)
                return
            print(f"  [{topic}]  {event}")
            count += 1
            if max_events and count >= max_events:
                _LOG.info("Received %d events for topic %r — done", count, topic)
                return


async def main(topics: list[str], max_events: int) -> None:
    """Connect and subscribe to one or more topics concurrently.

    Args:
        topics: List of topic strings to subscribe to.
        max_events: Maximum events per topic before exiting (0 = run forever).
    """
    try:
        async with asyncio.TaskGroup() as tg:
            async with SecureReqClient(
                rep_addr=DEFAULT_REP_URL,
                client_signing_key=load_signing_key(_CLIENT_KEY_PATH),
                server_verify_key=SERVER_VERIFY_KEY
            ) as req_client:
                _LOG.info("Connecting to server at %s", DEFAULT_REP_URL)

                for topic in topics:
                    _LOG.info("Subscribing to topic %r", topic)
        
                    # Send subscription request
                    subscription_request = SubscribeRequest.from_topic(topic)
                    await req_client.asend(subscription_request.to_json())

                    # Receive response
                    response_raw = await req_client.arecv()

                    # Parse response
                    response = SubscribeResponse.from_json(response_raw)
                    _LOG.info("Received subscription response for topic %r: pair_addr=%s",
                        topic, response.pair_addr
                    )

                    # Start a task to stream events for this topic.
                    tg.create_task(stream_topic(response, topic, max_events))


    except nng.NngClosed:
        _LOG.error("Connection to server closed")
    except PermissionError as exc:
        _LOG.error("Subscription rejected: %s", exc)
    except Exception:
        _LOG.exception("Server identity verification FAILED — possible rogue server, aborting.")


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--topics",
        nargs="+",
        default=["sensors"],
        metavar="TOPIC",
        help="Topics to subscribe to (default: sensors)",
    )
    parser.add_argument(
        "--max-events",
        type=int,
        default=10,
        metavar="N",
        help="Stop after N events per topic; 0 = run forever (default: 10)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    try:
        asyncio.run(main(args.topics, args.max_events))
    except KeyboardInterrupt:
        print("\nClient interrupted.")
    except ExceptionGroup as eg:
        # TaskGroup wraps task exceptions in an ExceptionGroup.
        for exc in eg.exceptions:
            if isinstance(exc, PermissionError):
                _LOG.error("Subscription rejected: %s", exc)
            elif isinstance(exc, nacl.exceptions.BadSignatureError):
                _LOG.error("Security error: %s", exc)
            else:
                raise
