#!/usr/bin/env python3
"""Subscription server — run this before starting any client.

Architecture
------------
A single :class:`nng.RepSocket` listens for subscription requests on
``REP_URL``.  When a request arrives from an authorized client it:

1. Validates the client's Ed25519 signature.
2. Delegates to :class:`~common.SecurePairServer`, which generates ephemeral
   keys, binds the PAIR listener, sends the signed response, and completes
   the mutual-auth handshake.
3. Spawns a background task that streams JSON events over the authenticated,
   encrypted PAIR channel.

Multiple clients may be subscribed concurrently.  Each gets its own PAIR
socket and its own asyncio task.  The REP loop remains responsive throughout.

Usage
-----
    python server.py [--transport tcp|ipc|inproc] [--interval SECONDS]
"""

from __future__ import annotations

import argparse
import asyncio
from collections.abc import AsyncGenerator
from contextlib import aclosing
import datetime
import json
import logging
import math
import os
import pathlib
from typing import Any, override

import nacl.exceptions
import nacl.signing

import nng

from common import (
    DEFAULT_REP_URL,
    DEFAULT_EVENT_INTERVAL_S,
    SubscribeRequest,
    SubscribeResponse
)
from secure_sockets.protocol_utils import (
    ErrorResponse,
    pick_pair_addr
)
from secure_sockets.secure_pair import (
    SecurePairServer,
)
from secure_sockets.secure_rep import (
    SecureRepServer
)
from secure_sockets.security_utils import (
    derive_verify_key,
    load_signing_key,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_HERE = pathlib.Path(__file__).parent

#: Path to the server's long-term Ed25519 signing key.
_SERVER_KEY_PATH = _HERE / "keys" / "server_sign.key"

#: Hex-encoded Ed25519 verify keys of clients that are allowed to subscribe.
#: Generated by gen_keys.py — paste the 'client' verify_key here.
AUTHORIZED_CLIENT_KEYS: frozenset[nacl.signing.VerifyKey] = frozenset([
    nacl.signing.VerifyKey(bytes.fromhex(
        "bebe88ef6e5bd5979834368d85481483c78a13107167c4d440b97325535e7064"
    ))
])

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
_LOG = logging.getLogger("server")


# ---------------------------------------------------------------------------
# Event generator
# ---------------------------------------------------------------------------


async def generate_events(
    topic: str, *, interval: float
) -> AsyncGenerator[dict[str, Any], None]:
    """Yield one JSON-serialisable event every *interval* seconds.

    Args:
        topic: The topic string requested by the client.
        interval: Emission cadence in seconds.

    Yields:
        A dict with ``topic``, ``seq``, ``ts``, and ``value`` fields.
    """
    seq = 0
    while True:
        await asyncio.sleep(interval)
        seq += 1
        yield {
            "topic": topic,
            "seq": seq,
            "ts": datetime.datetime.now(tz=datetime.timezone.utc).isoformat(),
            "value": round(math.sin(seq * 0.3), 6),
        }



# ---------------------------------------------------------------------------
# Per-client PAIR session
# ---------------------------------------------------------------------------

class EphemeralPairServer(SecurePairServer):
    """Server for the REP/REQ subscription protocol with post-handshake token verification."""

    __slots__ = {
        "_connection_token": "32-byte opaque token expected from client after handshake.",
    }

    _connection_token: bytes | None
    _url: str

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self._connection_token = None

    @staticmethod
    def find_available_addr_and_create(
        authorized_vks: frozenset[nacl.signing.VerifyKey],
        server_signing_key: nacl.signing.SigningKey,
        transport: str,
        connection_token: bytes,
    ) -> EphemeralPairServer:
        """Find an available address and create a PAIR socket bound to it.

        Args:
            authorized_vks: The set of authorized client verify keys.
            server_signing_key: The server's signing key.
            transport: NNG transport to use (e.g. ``tcp``, ``ipc``, ``inproc``).
            connection_token: The opaque token expected from the client after handshake.
        """
        pair_addr = pick_pair_addr(transport)
        server = EphemeralPairServer.create(
            authorized_vks,
            server_signing_key,
            pair_addr
        )
        server._connection_token = connection_token
        return server

    @override
    def _connect(self) -> None:
        """PAIR handshake then token verification (sync)."""
        super()._connect()
        token = self.recv()
        if token != self._connection_token:
            self._pair.close()
            raise PermissionError("Connection token mismatch — client did not go through subscription")

    @override
    async def _aconnect(self) -> None:
        """PAIR handshake then token verification (async)."""
        await super()._aconnect()
        token = await self.arecv()
        if token != self._connection_token:
            self._pair.close()
            raise PermissionError("Connection token mismatch — client did not go through subscription")


async def serve_client(
    srv: EphemeralPairServer,
    feed: AsyncGenerator[dict[str, Any], None],
) -> None:
    """Complete the handshake and stream events to one client.

    This coroutine is launched as a fire-and-forget task
    by the subscription manager once the REP handshake is done and the PAIR
    server is ready.  It performs the PAIR handshake, then enters a loop to
    stream events until the client disconnects or an error occurs.

    Args:
        srv: The PAIR server instance, already configured with the client's verify key
            and the connection token.
        feed: An async generator yielding JSON-serialisable events to send to the client.
    """
    client_id = os.urandom(6).hex()  # Dummy client ID for logging 
    try:
        async with aclosing(feed) as feed:
            async with srv as conn:
                _LOG.info("Client %s handshake complete — beginning streaming", client_id)
                async for event in feed:
                    binary = json.dumps(event, separators=(",", ":")).encode("utf-8")
                    await conn.asend(binary)
                    _LOG.debug("Client %s → seq=%s", client_id, event["seq"])
    except TimeoutError:
        _LOG.warning("Client %s handshake timed out — dropping connection", client_id)
    except (nacl.exceptions.BadSignatureError, ValueError) as exc:
        _LOG.warning("Client %s handshake FAILED: %s", client_id, exc)
    except nng.NngClosed:
        _LOG.info("Client %s disconnected", client_id)
    except asyncio.CancelledError:
        _LOG.info("Client %s task cancelled", client_id)
        raise

# ---------------------------------------------------------------------------
# Connection Req server
# ---------------------------------------------------------------------------

class SubscriptionReqServer(SecureRepServer):
    """Secure REP server that handles subscription requests and spawns PAIR servers.

    This class is responsible for the REP-side handshake and response to
    subscription requests.  The actual PAIR handshake and event streaming is
    handled by :class:`~common.SecurePairServer` in the per-client tasks.
    """

    __slots__ = {
        "_transport": "NNG transport for PAIR sockets (e.g. tcp, ipc, inproc).",
    }

    _transport: str

    def __init__(
        self,
        server_signing_key: nacl.signing.SigningKey,
        authorized_vks: frozenset[nacl.signing.VerifyKey],
        transport: str
    ) -> None:
        super().__init__(server_signing_key, authorized_vks)
        self._transport = transport

    @override
    async def conversation(self, conv) -> None:
        assert self._tg is not None
        _LOG.info(f"Starting new conversation with {conv.pipe.get_peer_addr()}")

        while True:
            # Get subscription topic from the client
            raw = await conv.arecv()

            # Interprete the request
            try:
                req = SubscribeRequest.from_json(raw)
            except (ValueError, KeyError) as exc:
                _LOG.warning("Malformed subscription request: %s", exc)
                await conv.asend(ErrorResponse(reason=str(exc)).to_json())
                raise # End conversation

            # prepare random token for client to send back after PAIR handshake
            token = os.urandom(32)

            # Spawn the PAIR server and send the response (url + random token)
            pair = EphemeralPairServer.find_available_addr_and_create(
                AUTHORIZED_CLIENT_KEYS,
                self._server_signing_key,
                self._transport,
                token
            )
            # TODO
            response = SubscribeResponse.create(
                pair.pair_addr, token
            )

            # Reply to client (the server already listens for connections)
            await conv.asend(response.to_json())

            # Create the pair feed
            feed = generate_events(req.topic, interval=DEFAULT_EVENT_INTERVAL_S)

            # Start the PAIR conversation in a new task
            self._tg.create_task(
                serve_client(pair, feed),
                name=f"client-{req.topic}-{os.urandom(3).hex()}"
            )
        # Return automatically when client disconnects (arecv will raise ConnectionResetError))
# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


async def main(transport: str, event_interval: float) -> None:
    """Run the subscription server.

    Args:
        transport: NNG transport for PAIR sockets.
        event_interval: Seconds between emitted events.
    """
    server_signing_key = load_signing_key(_SERVER_KEY_PATH)
    server_vk_hex = derive_verify_key(server_signing_key).encode().hex()
    _LOG.info("Server identity  verify_key = %s", server_vk_hex)
    _LOG.info("Listening for subscriptions on %s  (transport=%s)", DEFAULT_REP_URL, transport)

    server = SubscriptionReqServer(
        server_signing_key=server_signing_key,
        authorized_vks=AUTHORIZED_CLIENT_KEYS,
        transport=transport
    )
    async with asyncio.TaskGroup() as tg:
        server.serve(tg, DEFAULT_REP_URL)
    _LOG.info("Server shutting down")


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--transport",
        choices=["tcp", "ipc", "inproc"],
        default="tcp",
        help="Transport for the PAIR feed socket (default: tcp)",
    )
    parser.add_argument(
        "--interval",
        type=float,
        default=DEFAULT_EVENT_INTERVAL_S,
        metavar="SECONDS",
        help="Event emission interval in seconds (default: %(default)s)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    try:
        asyncio.run(main(args.transport, args.interval))
    except KeyboardInterrupt:
        print("\nServer interrupted — shutting down.")
