# This file is auto-generated by stubs/generate_stubs.py – do not edit manually.
# Re-run the script after changing any .pxi / .pyx source.

import concurrent.futures
import datetime
import sys
from collections.abc import AsyncGenerator, Callable
from typing import Any, ClassVar, Self

if sys.version_info >= (3, 12):
    from collections.abc import Buffer
else:
    from typing import TypeAlias
    Buffer: TypeAlias = memoryview

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class NngError(Exception):
    """
    Base exception for all nng errors.

    ``code`` is the raw nng error integer.
    """
    code: int
    def __init__(self, code: int, message: str | None = None) -> None: ...
    def __str__(self) -> str: ...

class NngTimeout(NngError, TimeoutError):
    """NNG_ETIMEDOUT – operation timed out."""
    ...

class NngConnectionRefused(NngError, ConnectionRefusedError):
    """NNG_ECONNREFUSED – connection refused."""
    ...

class NngClosed(NngError):
    """NNG_ECLOSED – socket / pipe / aio is closed."""
    ...

class NngAgain(NngError):
    """NNG_EAGAIN – operation would block in non-blocking mode."""
    ...

class NngNotSupported(NngError, NotImplementedError):
    """NNG_ENOTSUP – operation not supported by this protocol."""
    ...

class NngAddressInUse(NngError, OSError):
    """NNG_EADDRINUSE – address already in use."""
    ...

class NngPermission(NngError, PermissionError):
    """NNG_EPERM – permission denied."""
    ...

class NngCanceled(NngError):
    """NNG_ECANCELED – operation was cancelled."""
    ...

class NngConnectionReset(NngError, ConnectionResetError):
    """NNG_ECONNRESET – connection reset by peer."""
    ...

class NngConnectionAborted(NngError, ConnectionAbortedError):
    """NNG_ECONNABORTED – connection aborted."""
    ...

class NngNoMemory(NngError, MemoryError):
    """NNG_ENOMEM – out of memory."""
    ...

class NngInvalidArgument(NngError, ValueError):
    """NNG_EINVAL – invalid argument."""
    ...

class NngState(NngError):
    """NNG_ESTATE – incorrect state for this operation."""
    ...

class NngAuthError(NngError):
    """NNG_EPEERAUTH – peer authentication failed."""
    ...

class NngCryptoError(NngError):
    """NNG_ECRYPTO – cryptographic error."""
    ...
# ---------------------------------------------------------------------------
# Pipe lifecycle enum
# ---------------------------------------------------------------------------

class PipeStatus(int):
    """
    Lifecycle state of a :class:`Pipe`.

    * ``ADDING``  – the pipe has been created and negotiated (ADD_PRE event).
      The :attr:`Socket.on_new_pipe` callback fires at this point.
    * ``ACTIVE``  – the pipe is fully active (ADD_POST event).
      The pipe's own ``on_status_change`` callback fires here.
    * ``REMOVED`` – the pipe has been closed (REM_POST event).
      The pipe's ``on_status_change`` callback fires, then the pipe is
      removed from :attr:`Socket.pipes`.
    """
    ADDING: ClassVar[PipeStatus]
    ACTIVE: ClassVar[PipeStatus]
    REMOVED: ClassVar[PipeStatus]

# ---------------------------------------------------------------------------
# Core types
# ---------------------------------------------------------------------------

class Message:
    """
    A bytes buffer managed by nng.

    Messages are the unit of data transfer in nng.  They consist of a header
    and a body, which can be edited.  The body supports the buffer protocol
    for zero-copy access to the underlying nng buffer.

    When passing any data to send methods, a Message is internally
    constructed to hold a copy of that data.

    Using Message directly to build your message enables to save on
    a data copy which can make a difference for large message.

    Another usage of Message is to forward message from a socket
    to another. `recv` methods return a Message instance which
    can be directly passed to again to `send` methods. This avoids
    a buffer copy. In this use case, it can be useful to
    append or modify the message before forwarding it. For that use,
    Message provides methods to resize/trim/append data.

    When a Message is sent to a send method (except when send fails),
    the ownership of its content is passed to NNG, and the Message
    cannot be used anymore. `dup()` can be used to create an independent
    copy of the Message if you want to reuse the same content for multiple sends.

    For the reason above, when writing into a Message using a wrapper object
    (for instance memoryview or numpy asarray), you must release the wrapper
    objects before sending the Message, otherwise the send will fail with a
    PermissionError.

    Examples:

    Build a message from bytes and send it through a socket::

        msg = Message(b"hello") # create a message and copies to it "hello"
        sock.send(msg)          # ownership of msg's content is transferred to nng

    Fill as 2D array and send it::

        msg = Message(size=10*10*4)  # pre-allocate a message body of 400 bytes
        arr = np.asarray(msg, shape=(10, 10), dtype=np.float32)
        arr[:] = np.random.rand(10, 10) # fill the message body with random data
        del arr                         # release the numpy array wrapper
        sock.send(msg)  # ownership of msg's content is transferred to nng

    Receive a message and forward it after appending an ID::

        msg = sock1.recv()     # receive a message from sock1
        msg.append_u64(12345)  # append an ID to the message body
        sock2.send(msg)        # forward the same message to sock2 (zero-copy)
    """
    def __init__(self, data: bytes | Buffer | bytearray | str | None = None, *, size: int = 0) -> None:
        """
        Allocate a new message.

        Parameters
        ----------
        data:
            Initial body (bytes / bytearray / buffer). *size* is ignored
            when *data* is provided.
            str is accepted, in which case it is encoded as UTF-8.
        size:
            Pre-allocate a body of *size* zero bytes.
        """
        ...

    @property
    def body(self) -> memoryview:
        """Zero-copy writeable view of the message body."""
        ...

    @property
    def header(self) -> bytes:
        """
        Copy of the message header as *bytes*.

        The header is a separate byte buffer reserved
        for internal use by nng.
        """
        ...

    @property
    def pipe(self) -> Pipe | None:
        """
        The :class:`Pipe` this message arrived on, or ``None``.

        Returns ``None`` if:
            - The message was not received over a socket pipe (fresh allocation)
            - The message was received over a pipe that has since been closed.

        Else returns the pipe.
        """
        ...

    @property
    def pipe_id(self) -> int:
        """ID of the pipe this message arrived on (0 if not set)."""
        ...

    def append(self, data: bytes | Message | Buffer | bytearray | str) -> None:
        """Append *data* to the end of the body."""
        ...

    def append_u16(self, v: int) -> None:
        """Append a 16-bit unsigned integer in network byte order to the end of the body."""
        ...

    def append_u32(self, v: int) -> None:
        """Append a 32-bit unsigned integer in network byte order to the end of the body."""
        ...

    def append_u64(self, v: int) -> None:
        """Append a 64-bit unsigned integer in network byte order to the end of the body."""
        ...

    def chop(self, n: int) -> None:
        """Remove *n* bytes from the end of the body."""
        ...

    def chop_u16(self) -> int:
        """Remove and return a 16-bit unsigned integer in network byte order from the end of the body."""
        ...

    def chop_u32(self) -> int:
        """Remove and return a 32-bit unsigned integer in network byte order from the end of the body."""
        ...

    def chop_u64(self) -> int:
        """Remove and return a 64-bit unsigned integer in network byte order from the end of the body."""
        ...

    def clear(self) -> None:
        """
        Discard all body bytes (append).

        Resets the body length to zero without releasing the pre-allocated
        capacity. Use this to reuse a message buffer with append calls
        without paying for a new allocation.
        """
        ...

    def dup(self) -> Message:
        """Return an independent copy of this message."""
        ...

    def insert(self, data: bytes | Message | Buffer | bytearray | str) -> None:
        """Prepend *data* to the front of the body."""
        ...

    def reserve(self, capacity: int) -> None:
        """
        Ensure the body buffer has at least *capacity* bytes pre-allocated.

        Pre-reserving the total anticipated size avoids many small
        reallocations when building a message incrementally with
        ``append`` / ``insert``.
        """
        ...

    def resize(self, new_size: int) -> None:
        """Resize the body to *new_size* bytes, truncating or zero-padding as needed."""
        ...

    def to_bytes(self) -> bytes:
        """Copy the message body into a new *bytes* object."""
        ...

    def trim(self, n: int) -> None:
        """Remove *n* bytes from the front of the body."""
        ...

    def trim_u16(self) -> int:
        """Remove and return a 16-bit unsigned integer in network byte order from the front of the body."""
        ...

    def trim_u32(self) -> int:
        """Remove and return a 32-bit unsigned integer in network byte order from the front of the body."""
        ...

    def trim_u64(self) -> int:
        """Remove and return a 64-bit unsigned integer in network byte order from the front of the body."""
        ...

    def __buffer__(self, flags: Any) -> Any:
        """Return a buffer object that exposes the underlying memory of the object."""
        ...

    def __eq__(self, *args: Any, **kwargs: Any) -> bool:
        """True when both messages have identical body bytes (memcmp)."""
        ...

    def __ge__(self, value: Any) -> Any:
        """Return self>=value."""
        ...

    def __gt__(self, value: Any) -> Any:
        """Return self>value."""
        ...

    def __hash__(self) -> int:
        """Return hash(self)."""
        ...

    def __le__(self, value: Any) -> Any:
        """Return self<=value."""
        ...

    def __len__(self) -> int:
        """Return len(self)."""
        ...

    def __lt__(self, value: Any) -> Any:
        """Return self<value."""
        ...

    def __ne__(self, value: Any) -> bool:
        """Return self!=value."""
        ...

    def __release_buffer__(self, buffer: Any) -> Any:
        """Release the buffer object that exposes the underlying memory of the object."""
        ...

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...

    def __str__(self) -> str:
        """Return str(self)."""
        ...


class TlsCert:
    """
    X.509 certificate from a TLS peer or parsed from PEM/DER.
        
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Raise TypeError — use the class-method factories."""
        ...

    @property
    def alt_names(self) -> list[str]:
        """
        Subject Alternative Names (SANs), if any.

        Returns an ordered list of SAN strings.  DNS names appear as plain
        hostnames (``'example.com'``); IP addresses as ``'IP:192.0.2.1'``.
        Returns an empty list when no SANs are present.

        .. note::
            NNG iterates SANs with a stateful internal cursor.  This property
            drains all names on the **first** call and caches the result;
            subsequent calls return the same cached list.

        Raises:
            ValueError: If the certificate pointer is null.
            NngError: On unexpected errors from the TLS engine.
        """
        ...

    @property
    def issuer(self) -> str:
        """
        Full issuer distinguished name.

        Raises:
            ValueError: If the certificate pointer is null.
            NngError: If the TLS engine does not support this attribute.
        """
        ...

    @property
    def not_after(self) -> datetime.datetime:
        """
        Certificate validity end time as a UTC-aware :class:`datetime`.

        Raises:
            ValueError: If the certificate pointer is null.
            NngError: If the TLS engine does not support this attribute.
        """
        ...

    @property
    def not_before(self) -> datetime.datetime:
        """
        Certificate validity start time as a UTC-aware :class:`datetime`.

        Raises:
            ValueError: If the certificate pointer is null.
            NngError: If the TLS engine does not support this attribute.
        """
        ...

    @property
    def serial_number(self) -> str:
        """
        Serial number as a colon-separated hex string, e.g. ``'01:ab:cd:...'``.

        Raises:
            ValueError: If the certificate pointer is null.
            NngError: If the TLS engine does not support this attribute.
        """
        ...

    @property
    def subject(self) -> str:
        """
        Full subject distinguished name, e.g. ``'CN=example.com,O=Acme'``.

        Raises:
            ValueError: If the certificate pointer is null.
            NngError: If the TLS engine does not support this attribute.
        """
        ...

    @property
    def subject_cn(self) -> str:
        """
        Common name (CN) from the subject, e.g. ``'example.com'``.

        Modern certificates prefer Subject Alternative Names (SANs) over CN
        for identity.  Use :attr:`alt_names` when verifying host identity.

        Raises:
            ValueError: If the certificate pointer is null.
            NngError: If the TLS engine does not support this attribute.
        """
        ...

    @classmethod
    def from_der(cls: Any, der: Any) -> TlsCert:
        """
        Parse a DER-encoded X.509 certificate.

        Args:
            der: Raw DER bytes of the certificate.

        Returns:
            A new :class:`TlsCert`.

        Raises:
            NngError: If the DER is invalid or no TLS engine is loaded.
        """
        ...

    @classmethod
    def from_pem(cls: Any, pem: Any) -> TlsCert:
        """
        Parse a PEM-encoded X.509 certificate.

        Args:
            pem: PEM text (``str`` or ``bytes``).  When multiple certificates
                are concatenated only the first is used.

        Returns:
            A new :class:`TlsCert`.

        Raises:
            NngError: If the PEM is invalid or no TLS engine is loaded.
        """
        ...

    def to_der(self) -> bytes:
        """
        Export the certificate as DER-encoded bytes.

        Useful for interoperability with other crypto libraries (OpenSSL,
        mbedTLS, etc.).

        Returns:
            Raw DER bytes.

        Raises:
            ValueError: If the certificate pointer is null.
        """
        ...

    def __bool__(self) -> bool:
        """True if self else False"""
        ...

    def __eq__(self, value: Any) -> bool:
        """Return self==value."""
        ...

    def __ge__(self, value: Any) -> Any:
        """Return self>=value."""
        ...

    def __gt__(self, value: Any) -> Any:
        """Return self>value."""
        ...

    def __hash__(self) -> int:
        """Return hash(self)."""
        ...

    def __le__(self, value: Any) -> Any:
        """Return self<=value."""
        ...

    def __lt__(self, value: Any) -> Any:
        """Return self<value."""
        ...

    def __ne__(self, value: Any) -> bool:
        """Return self!=value."""
        ...

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...


class TlsConfig:
    """
    TLS configuration object for securing nng connections.

    Pass as the ``tls=`` argument to :meth:`Socket.add_dialer` or
    :meth:`Socket.add_listener`.

    Instances are created exclusively through the class-method factories:

    * :meth:`for_client` — certificate-based TLS client.
    * :meth:`for_server` — certificate-based TLS server.
    * :meth:`for_psk_client` — PSK-based TLS client.
    * :meth:`for_psk_server` — PSK-based TLS server (multiple identities).

    A single :class:`TlsConfig` may be shared across multiple dialers and
    listeners.  Once attached to a started dialer or listener the
    configuration is locked by nng and cannot be changed.

    **PSK engine compatibility**

    :meth:`for_psk_client` and :meth:`for_psk_server` are supported by all
    bundled engines, with one caveat: wolfSSL requires the
    ``NNG_SUPP_TLS_PSK`` compile-time flag; calling these factories on such a
    build raises :exc:`NngNotSupported`.

    Example (mTLS client)::

        cfg = TlsConfig.for_client(
            server_name="example.com",
            ca_pem=ca_bundle,
            cert_pem=my_cert,
            key_pem=my_key,
        )
        sock.add_dialer("tls+tcp://example.com:5555", tls=cfg).start()

    Example (TLS server)::

        cfg = TlsConfig.for_server(cert_file="/etc/ssl/server.pem")
        sock.add_listener("tls+tcp://0.0.0.0:5555", tls=cfg).start()
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Raise TypeError — use the class-method factories."""
        ...

    @classmethod
    def for_client(cls, *, server_name: str | None = None, ca_pem: str | None = None, crl_pem: str | None = None, ca_file: str | None = None, cert_pem: str | None = None, key_pem: str | None = None, cert_file: str | None = None, password: str | None = None, auth_mode: int | None = None, min_version: int | None = None, max_version: int | None = None) -> TlsConfig:
        """
        Create a :class:`TlsConfig` for certificate-based TLS client use.

        All parameters are keyword-only and optional; supply only those
        relevant to your use case.

        Args:
            server_name: Expected server hostname for SNI and cert verification.
            ca_pem:      PEM-encoded CA certificates for peer verification.
                         Multiple certificates can be concatenated.
            crl_pem:     PEM-encoded CRL to pair with *ca_pem*.  wolfSSL
                         ignores this unless compiled with
                         ``NNG_WOLFSSL_HAVE_CRL``.
            ca_file:     Path to a PEM file with CA certs (and optional CRLs).
            cert_pem:    PEM-encoded client certificate (requires *key_pem*).
            key_pem:     PEM-encoded private key for *cert_pem*.  Encrypted
                         keys require *password*.
            cert_file:   Path to a PEM file containing both cert and key.
                         Encrypted keys require *password*.
            password:    Passphrase to decrypt *key_pem* or the key in
                         *cert_file*.
            auth_mode:   One of the ``TLS_AUTH_*`` constants.  Defaults to
                         ``TLS_AUTH_REQUIRED``.
            min_version: Minimum TLS version (``TLS_VERSION_1_2`` or
                         ``TLS_VERSION_1_3``).
            max_version: Maximum TLS version.  wolfSSL ignores this argument.

        Returns:
            A new :class:`TlsConfig` in client mode.

        Raises:
            ValueError: If *crl_pem* is set without *ca_pem*.
            NngCryptoError: If a certificate or private key cannot be parsed.
            NngNoMemory: If a memory allocation fails.
            NngNotSupported: If *min_version*/*max_version* specifies a TLS
                version unsupported by the active engine.
            NngError: If *ca_file* or *cert_file* cannot be opened
                (``NNG_ENOENT``) or read (``NNG_EACCESS``).
        """
        ...

    @classmethod
    def for_psk_client(cls, identity: str, key: bytes, *, min_version: int | None = None, max_version: int | None = None) -> TlsConfig:
        """
        Create a :class:`TlsConfig` for PSK-based TLS client use.

        Pre-shared key (PSK) is an alternative to certificate-based
        authentication that requires no CA infrastructure.

        *identity* is a printable string (up to ~64 bytes) that acts as a
        public identifier for this client.  Embedded NUL bytes are not
        supported.

        *key* is the shared secret used to derive session keys.  mbedTLS and
        wolfSSL limit key length to ``MBEDTLS_PSK_MAX_LEN`` (typically
        32 bytes); prefer 16–32 byte keys for widest compatibility.

        Certificate verification is **disabled** automatically.  Pure PSK
        ciphersuites do not exchange certificates, so requiring one would
        cause the TLS handshake to fail.

        Args:
            identity:    PSK identity string (analogous to a username).
            key:         PSK secret bytes.
            min_version: Minimum TLS version (``TLS_VERSION_1_2`` or
                         ``TLS_VERSION_1_3``).
            max_version: Maximum TLS version.  wolfSSL ignores this argument.

        Returns:
            A new :class:`TlsConfig` in client mode.

        Raises:
            NngNotSupported: On wolfSSL when ``NNG_SUPP_TLS_PSK`` is not set.
            NngCryptoError: If the key or identity is rejected by the engine.
            NngNoMemory: If a memory allocation fails.
        """
        ...

    @classmethod
    def for_psk_server(cls, psks: dict[str, bytes], *, min_version: int | None = None, max_version: int | None = None) -> TlsConfig:
        """
        Create a :class:`TlsConfig` for PSK-based TLS server use.

        PSK server configurations accept multiple client identities.  *psks*
        maps each identity string to its corresponding key bytes.

        When a PSK client connects, the engine looks up the client's identity
        in *psks* and uses the matching key to complete the handshake.

        Args:
            psks:        ``{identity: key}`` mapping of PSK pairs.  Must not
                         be empty.
            min_version: Minimum TLS version (``TLS_VERSION_1_2`` or
                         ``TLS_VERSION_1_3``).
            max_version: Maximum TLS version.  wolfSSL ignores this argument.

        Returns:
            A new :class:`TlsConfig` in server mode.

        Raises:
            ValueError: If *psks* is empty.
            NngNotSupported: On wolfSSL when ``NNG_SUPP_TLS_PSK`` is not set.
            NngCryptoError: If a key or identity is rejected by the engine.
            NngNoMemory: If a memory allocation fails.
        """
        ...

    @classmethod
    def for_server(cls, *, cert_pem: str | None = None, key_pem: str | None = None, cert_file: str | None = None, password: str | None = None, ca_pem: str | None = None, crl_pem: str | None = None, ca_file: str | None = None, auth_mode: int | None = None, min_version: int | None = None, max_version: int | None = None) -> TlsConfig:
        """
        Create a :class:`TlsConfig` for certificate-based TLS server use.

        All parameters are keyword-only and optional; supply only those
        relevant to your use case.

        On **mbedTLS** and **OpenSSL** a server may register multiple
        cert+key pairs (e.g. RSA + ECDSA) so the engine can select the best
        match per client.  This factory supports a single pair; for
        multi-algorithm servers assemble the config with the C API directly.
        On wolfSSL, *cert_pem* / *cert_file* replaces any previously set cert.

        Args:
            cert_pem:    PEM-encoded server certificate (requires *key_pem*).
            key_pem:     PEM-encoded private key for *cert_pem*.  Encrypted
                         keys require *password*.
            cert_file:   Path to a PEM file containing both cert and key.
            password:    Passphrase to decrypt the private key.
            ca_pem:      PEM-encoded CA certificates for client cert
                         verification (mTLS).  Required when *auth_mode* is
                         not ``TLS_AUTH_NONE``.
            crl_pem:     PEM-encoded CRL to pair with *ca_pem*.  wolfSSL
                         ignores this unless compiled with
                         ``NNG_WOLFSSL_HAVE_CRL``.
            ca_file:     Path to a PEM file with CA certs for client
                         verification.
            auth_mode:   One of the ``TLS_AUTH_*`` constants.  Defaults to
                         ``TLS_AUTH_NONE``.
            min_version: Minimum TLS version (``TLS_VERSION_1_2`` or
                         ``TLS_VERSION_1_3``).
            max_version: Maximum TLS version.  wolfSSL ignores this argument.

        Returns:
            A new :class:`TlsConfig` in server mode.

        Raises:
            ValueError: If *crl_pem* is set without *ca_pem*.
            NngCryptoError: If a certificate or private key cannot be parsed.
            NngNoMemory: If a memory allocation fails.
            NngNotSupported: If *min_version*/*max_version* specifies a TLS
                version unsupported by the active engine.
            NngError: If *ca_file* or *cert_file* cannot be opened
                (``NNG_ENOENT``) or read (``NNG_EACCESS``).
        """
        ...

    def __repr__(self, *args: Any, **kwargs: Any) -> str:
        """Return a debug string for this config."""
        ...


class SocketAddr:
    """Utility for converting nng_sockaddr to a URL string."""
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...

    @property
    def port(self) -> int:
        """Port number, or 0 if not applicable."""
        ...

    def __eq__(self, value: Any) -> bool:
        """Return self==value."""
        ...

    def __ge__(self, value: Any) -> Any:
        """Return self>=value."""
        ...

    def __gt__(self, value: Any) -> Any:
        """Return self>value."""
        ...

    def __hash__(self) -> int:
        """Return hash(self)."""
        ...

    def __le__(self, value: Any) -> Any:
        """Return self<=value."""
        ...

    def __lt__(self, value: Any) -> Any:
        """Return self<value."""
        ...

    def __ne__(self, value: Any) -> bool:
        """Return self!=value."""
        ...

    def __str__(self) -> str:
        """Return str(self)."""
        ...


class Pipe:
    """
    Non-owning wrapper for a single nng pipe (physical connection).

    Pipes are created automatically:

    * A :class:`Dialer` creates one pipe when its outbound connection succeeds
      and recreates it transparently after each reconnect.
    * A :class:`Listener` creates one pipe for every inbound connection it
      accepts.

    Applications normally never create ``Pipe`` objects directly.  They appear
    as arguments to callbacks registered with :attr:`Socket.on_new_pipe`.
    The ``Pipe`` object is **non-owning** — closing it kicks the connection;
    the underlying socket is unaffected.
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...

    @property
    def dialer(self) -> Dialer | None:
        """The :class:`Dialer` that created this pipe, or ``None``."""
        ...

    @property
    def id(self) -> int:
        """Numeric pipe ID."""
        ...

    @property
    def listener(self) -> Listener | None:
        """The :class:`Listener` that accepted this pipe, or ``None``."""
        ...

    @property
    def on_status_change(self) -> Callable[[], None] | None:
        """Callback fired when this pipe transitions to ACTIVE or REMOVED."""
        ...
    @on_status_change.setter
    def on_status_change(self, value: Callable[[], None]) -> None: ...

    @property
    def socket(self) -> Socket | None:
        """The owning :class:`Socket`, or ``None`` if no longer tracked."""
        ...

    @property
    def status(self) -> PipeStatus:
        """Current :class:`PipeStatus` of this pipe."""
        ...

    @property
    def tcp_keepalive(self) -> bool:
        """
        ``True`` when TCP keep-alive probes were enabled at connection time.

        Captured once at pipe creation.  Always ``False`` for non-TCP pipes.
        """
        ...

    @property
    def tcp_nodelay(self) -> bool:
        """
        ``True`` when TCP_NODELAY (Nagle disabled) was active at connection time.

        Captured once at pipe creation.  Always ``False`` for non-TCP pipes.
        """
        ...

    @property
    def tls_peer_cn(self) -> str | None:
        """
        Common name (CN) from the peer's TLS certificate, or ``None``.

        Returns ``None`` for non-TLS pipes or when no certificate was
        presented.  Captured once at pipe creation.
        """
        ...

    @property
    def tls_verified(self) -> bool:
        """
        ``True`` when the peer's TLS certificate was successfully verified.

        Returns ``False`` for non-TLS pipes or when peer verification was not
        required / did not take place.  Captured once at pipe creation.
        """
        ...

    def close(self) -> None:
        """
        Forcibly close this connection.

        The underlying transport is terminated immediately.  Dialers attempt to
        reconnect; listeners wait for a new inbound connection.  In-flight
        sends/receives on this pipe fail immediately.

        If a change callback is registered it fires when the close completes.

        If a pipe is closed several times, only the first call has an effect.
        Subsequent calls are no-ops.
        """
        ...

    def get_peer_addr(self) -> SocketAddr:
        """Remote peer address."""
        ...

    def get_peer_cert(self) -> TlsCert | None:
        """
        Return the peer's TLS certificate, or ``None`` for non-TLS pipes.

        The certificate data is captured at pipe creation time and is
        fully independent of the pipe's lifetime.  The returned
        :class:`TlsCert` is an **owning** object; it is safe to keep it
        after the pipe is closed.

        Returns:
            An owning :class:`TlsCert`, or ``None`` if this is not a TLS
            pipe or no certificate was presented.
        """
        ...

    def get_self_addr(self) -> SocketAddr:
        """Local address."""
        ...

    def __eq__(self, value: Any) -> bool:
        """Return self==value."""
        ...

    def __ge__(self, value: Any) -> Any:
        """Return self>=value."""
        ...

    def __gt__(self, value: Any) -> Any:
        """Return self>value."""
        ...

    def __hash__(self) -> int:
        """Return hash(self)."""
        ...

    def __index__(self) -> int:
        """Return self converted to an integer, if self is suitable for use as an index into a list."""
        ...

    def __le__(self, value: Any) -> Any:
        """Return self<=value."""
        ...

    def __lt__(self, value: Any) -> Any:
        """Return self<value."""
        ...

    def __ne__(self, value: Any) -> bool:
        """Return self!=value."""
        ...

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...


class Dialer:
    """
    An outbound endpoint that connects a :class:`Socket` to a remote peer.

    Each ``Dialer`` establishes and maintains **exactly one outbound connection**
    (called a *pipe*) to its target address.  If the connection is lost, the
    dialer automatically retries in the background using exponential back-off
    between :attr:`reconnect_min_ms` and :attr:`reconnect_max_ms`.

    A single socket can have **multiple dialers**, each pointing at a different
    address.  All resulting pipes are pooled at the socket level and the
    protocol decides how to distribute messages across them.

    Returned by :meth:`Socket.add_dialer` (not yet started; call :meth:`start`
    to initiate the connection).

    All configuration options (TLS, reconnect intervals, timeouts) are set
    via :meth:`Socket.add_dialer` before the dialer is started.
    The dialer's configuration is **locked** and
    individual options can no longer be changed.

    .. note::
        The dialer/listener distinction is **orthogonal** to the
        client/server role in the protocol.  For example, a ``REP`` socket
        may use a dialer to connect to a ``REQ`` socket's listener.

    The dialer is closed automatically when its parent socket is closed.
    It is also closed explicitly via :meth:`close` or when used as a
    context manager.

    The properties on this class are **read-only** and exist solely for
    inspection after the fact.

    Use as a context manager to ensure the endpoint is closed::

        with sock.add_dialer("tcp://127.0.0.1:5555",
                             reconnect_min_ms=100, reconnect_max_ms=5000) as d:
            d.start()
            ...
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...

    @property
    def id(self) -> int:
        """The numeric dialer ID, or 0 if the dialer has been closed."""
        ...

    @property
    def pipe(self) -> Pipe | None:
        """The active :class:`Pipe` for this dialer, or ``None`` if not connected."""
        ...

    @property
    def reconnect_max_ms(self) -> Any:
        """
        Maximum reconnect interval in milliseconds.

        The dialer will not wait longer than this between retries.  ``0``
        means use :attr:`reconnect_min_ms` as a fixed interval.  Configured
        at construction time via :meth:`Socket.add_dialer`.

        Raises
        ------
        NngClosed
            If the dialer has been closed.
        """
        ...

    @property
    def reconnect_min_ms(self) -> Any:
        """
        Minimum reconnect interval in milliseconds.

        After a connection is lost the dialer waits at least this long before
        the first retry.  Subsequent retries use exponential back-off up to
        :attr:`reconnect_max_ms`.  Configured at construction time via
        :meth:`Socket.add_dialer`.

        Raises
        ------
        NngClosed
            If the dialer has been closed.
        """
        ...

    @property
    def socket(self) -> Socket | None:
        """The parent :class:`Socket` for this dialer."""
        ...

    @property
    def tcp_keepalive(self) -> bool:
        """
        ``True`` when TCP keep-alive probes are enabled on this dialer.

        This corresponds to the ``NNG_OPT_TCP_KEEPALIVE`` option.  Configured
        at construction time via :meth:`Socket.add_dialer`.

        Raises
        ------
        NngClosed
            If the dialer has been closed.
        NngNotSupported
            If this dialer does not use the TCP transport.
        """
        ...

    @property
    def tcp_nodelay(self) -> bool:
        """
        ``True`` when TCP_NODELAY (Nagle disabled) is active on this dialer (Default).

        This corresponds to the ``NNG_OPT_TCP_NODELAY`` option.  Configured
        at construction time via :meth:`Socket.add_dialer`.

        Raises
        ------
        NngClosed
            If the dialer has been closed.
        NngNotSupported
            If this dialer does not use the TCP transport.
        """
        ...

    def close(self) -> None:
        """
        Close the dialer and tear down its active connection, if any.

        The pipe (connection) associated with this dialer is closed immediately.
        Any in-flight sends or receives on that pipe will fail.  The parent
        socket remains open and its other pipes are unaffected.

        If the dialer is already closed this method is a no-op (no exception
        is raised).
        """
        ...

    def start(self, *, block: bool = True) -> None:
        """
        Initiate the outbound connection.

        Must be called after :meth:`Socket.add_dialer` to actually begin
        connecting.  The dialer will maintain the connection and reconnect
        automatically if it is dropped.  Once started, the dialer's
        configuration is **locked** and cannot be changed.

        Parameters
        ----------
        block:
            If *True* (default) block until the first connection succeeds
            (raises on error).  If *False*, return immediately; nng retries
            in the background even if the initial attempt fails — errors
            such as ``NngConnectionRefused`` will **not** be raised in that
            case, and connection progress is opaque.

        Raises
        ------
        NngClosed
            If the dialer or socket have been closed.
        NngState
            If the dialer has already been started.
        NngConnectionRefused
            The remote peer refused the connection (blocking mode only).
        NngConnectionReset
            The remote peer reset the connection (blocking mode only).
        NngAuthError
            TLS peer authentication or authorization failed (blocking mode only).
        NngNoMemory
            Insufficient memory to complete the operation.
        NngError
            Other transport-level errors (e.g. ``NNG_EUNREACHABLE``,
            ``NNG_EPROTO``).
        """
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, *_: Any) -> None:
        ...

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...


class Listener:
    """
    An inbound endpoint that accepts connections on behalf of a :class:`Socket`.

    Unlike a :class:`Dialer` (which maintains a single outbound connection),
    a ``Listener`` can accept **any number of simultaneous inbound connections**.
    Each accepted connection becomes a *pipe* in the parent socket's pipe pool.

    A single socket can have **multiple listeners**, each bound to a different
    address or transport.  For example, a server can listen on both TCP and IPC
    at the same time, and all clients are handled through the same socket.

    Returned by :meth:`Socket.add_listener` (not yet started; call
    :meth:`start` to begin accepting connections).

    All configuration options (TLS, per-pipe timeouts) are set via
    :meth:`Socket.add_listener` before the listener is created.  Once
    created the listener's configuration is **locked** and
    individual options can no longer be changed.

    .. note::
        The dialer/listener distinction is **orthogonal** to the
        client/server role in the protocol.  For example, a ``REQ`` socket
        may use a listener to accept connections from ``REP`` dialers.

    The listener is closed automatically when its parent socket is closed.
    It is also closed explicitly via :meth:`close` or when used as a
    context manager.

    The properties on this class are **read-only** and exist solely for
    inspection after the fact.

    Special behaviours:
        - Setting port 0 in a tcp url causes the listener to bind to an ephemeral port. The actual port
            can then be retrieved from the listener's address property after start() returns. This is a common
            technique for service discovery when combined with an out-of-band mechanism to share the port number
            with clients (e.g. a well-known "discovery" socket or an external service registry).
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...

    @property
    def id(self) -> int:
        """The numeric listener ID, or 0 if the listener has been closed."""
        ...

    @property
    def pipes(self) -> list[Pipe]:
        """The active :class:`Pipe`(s) for this listener."""
        ...

    @property
    def port(self) -> int:
        """
        The local port this listener is bound to, or 0 if not a TCP listener.

        For TCP listeners, this is the actual port number the listener is bound
        to. For non-TCP listeners, this property always returns 0.

        Note that for TCP listeners configured with port 0, the actual port is
        assigned by the OS at bind time and can be retrieved from this property
        after :meth:`start` returns.
        """
        ...

    @property
    def socket(self) -> Socket | None:
        """The parent :class:`Socket` for this listener."""
        ...

    @property
    def tcp_keepalive(self) -> bool:
        """
        ``True`` when TCP keep-alive probes are enabled on this listener.

        This corresponds to the ``NNG_OPT_TCP_KEEPALIVE`` option.  Configured
        at construction time via :meth:`Socket.add_listener`.

        Raises
        ------
        NngClosed
            If the listener has been closed.
        NngNotSupported
            If this listener does not use the TCP transport.
        """
        ...

    @property
    def tcp_nodelay(self) -> bool:
        """
        ``True`` when TCP_NODELAY (Nagle disabled) is active on this listener.

        This corresponds to the ``NNG_OPT_TCP_NODELAY`` option.  Configured
        at construction time via :meth:`Socket.add_listener`.

        Raises
        ------
        NngClosed
            If the listener has been closed.
        NngNotSupported
            If this listener does not use the TCP transport.
        """
        ...

    def close(self) -> None:
        """
        Stop accepting new connections and close all pipes this listener created.

        Already-established pipes that are actively transferring data will be
        closed immediately.  The parent socket remains open and any pipes from
        *other* listeners or dialers continue operating normally.

        If the listener is already closed this method is a no-op (no exception
        is raised).
        """
        ...

    def start(self) -> None:
        """
        Bind to the address and start accepting inbound connections.

        Must be called after :meth:`Socket.add_listener` to actually begin
        accepting connections.  Once started, the listener accepts unlimited
        simultaneous peers until :meth:`close` is called.  The listener's
        configuration is **locked** after this call and cannot be changed.

        Raises
        ------
        NngClosed
            If the listener or socket have been closed.
        NngState
            If the listener has already been started.
        NngAddressInUse
            The address is already in use by another listener.
        NngNoMemory
            Insufficient memory to complete the operation.
        NngError
            Other transport-level errors (e.g. permission denied binding
            to a privileged port).
        """
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, *_: Any) -> None:
        ...

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...


class Context:
    """
    A protocol context (nng_ctx).

    Provides an independent request/reply state machine on a shared socket,
    allowing many concurrent in-flight requests without raw mode::

        sock = ReqSocket()
        sock.add_dialer("tcp://127.0.0.1:5000").start()
        ctx  = sock.open_context()
        ctx.send_msg(Message(b"ping"))
        reply = ctx.recv_msg()
        ctx.close() # optional
    """
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...

    @property
    def id(self) -> int:
        ...

    @property
    def recv_timeout(self) -> int:
        """
        Receive timeout in ms (-1 = infinite, 0 = non-blocking).

        This affects all `recv`/`arecv`/`submit_recv` operations on this context,
        regardless of pipe, starting from the time this option is modified.

        Contexts inherit from the socket parameter at creation.
        """
        ...
    @recv_timeout.setter
    def recv_timeout(self, value: int) -> None: ...

    @property
    def send_timeout(self) -> int:
        """
        Send timeout in ms (-1 = infinite, 0 = non-blocking).

        This affects all `send`/`asend`/`submit_send` operations on this context, regardless of pipe,
        starting from the time this option is modified.

        Contexts inherit from the socket parameter at creation.
        """
        ...
    @send_timeout.setter
    def send_timeout(self, value: int) -> None: ...

    @property
    def socket(self) -> Socket | None:
        """
        The parent Socket for this context.

        Note: the context only holds a weak reference to the parent
        socket to avoid reference cycles, so this property may raise
        :exc:`RuntimeError` if no other references to the parent socket exist.
        """
        ...

    async def arecv(self) -> Message:
        """Receive a Message asynchronously through this context."""
        ...

    async def asend(self, data: bytes | Message | Buffer | bytearray | str) -> None:
        """Send a Message asynchronously through this context."""
        ...

    def close(self) -> None:
        ...

    def recv(self, *, nonblock: bool = False) -> Message:
        """Receive a Message through this context."""
        ...

    def send(self, data: bytes | Message | Buffer | bytearray | str, *, nonblock: bool = False) -> None:
        """Send a Message through this context (transfers ownership)."""
        ...

    def submit_recv(self) -> concurrent.futures.Future[Message]:
        """
        Receive asynchronously; return a concurrent.futures.Future → bytes.

        The future resolves to the received payload as ``bytes``.
        Can be called from any thread without a running event loop.
        """
        ...

    def submit_send(self, data: bytes | Message | Buffer | bytearray | str) -> concurrent.futures.Future[None]:
        """
        Send *data* (bytes-like) asynchronously; return a concurrent.futures.Future.

        The future resolves to ``None`` on success or raises an :exc:`NngError`
        on failure.  Can be called from any thread without a running event loop.
        """
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, *_: Any) -> None:
        ...

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...


class ReqContext(Context):
    """
    Independent REQ context on a :class:`ReqSocket`.

    REQ contexts have an independent send-receive state machine from their
    parent socket, allowing multiple concurrent requests.
    """
    @property
    def resend_time(self) -> int:
        """
        How long (ms) to wait for a reply before resending the request.

        Requests are automatically resent if the peer disconnects.

        resend_time adds a timer at which requests will be resent (even if no
        disconnection has been detected) to the peer until a reply is received.

        ``-1`` (the default) disables automatic resending (exception on disconnect)
        Setting a positive value provides automatic fault-tolerance when working with
        multiple REP peers, or possible packet loss. However it has the drawback
        of causing a pipe connection loss upon receiving a reply of the previous
        request after the resend timer has fired.

        Setting a < 1000ms resend_time requires tuning the socket `resend_tick`
        attribute to have real effect.

        Contexts inherit from the socket parameter at creation.
        """
        ...
    @resend_time.setter
    def resend_time(self, value: int) -> None: ...


class SubContext(Context):
    """
    Independent sub context on a :class:`SubSocket`.

    Sub contexts have an independant subscription state as their
    parent socket. They thus can be used to implement multiple logical
    subscribers sharing the same underlying socket.
    """
    @property
    def recv_buf(self) -> int:
        """
        Receive buffer depth (number of queued messages).

        Unlike other protocols, the SUB protocol enables a per context
        receive buffer depth, which limits the number of messages that can be
        queued for the subscriptions associated with this context.

        If the buffer is full, new messages are dropped according to
        the skip_older_on_full_queue policy.

        The default value is the one configured on the parent socket at the
        time of the socket creation (which is 128 by default).
        """
        ...
    @recv_buf.setter
    def recv_buf(self, value: int) -> None: ...

    @property
    def skip_older_on_full_queue(self) -> bool:
        """
        Whether to drop older messages when the receive queue is full.

        If True, when the receive queue is full, newer messages are kept and
        older unread messages are dropped.  Setting this option to ``False``
        reverses that behavior: older messages are kept and newer messages are
        dropped instead.

        The default value is the one configured on the parent socket at the
        time of the socket creation (which is True by default).
        """
        ...
    @skip_older_on_full_queue.setter
    def skip_older_on_full_queue(self, value: bool) -> None: ...

    def subscribe(self, prefix: bytes = b'') -> None:
        """
        Subscribe to messages whose body starts with *prefix*.

        An empty prefix subscribes to all messages.

        Contexts do not inherit from the socket parameter at creation,
        and start with an empty subscription set (no messages).
        """
        ...

    def unsubscribe(self, prefix: bytes = b'') -> None:
        """
        Unsubscribe from messages whose body starts with *prefix*.

        An empty prefix unsubscribes from all messages.
        """
        ...


class SurveyorContext(Context):
    """
    Independent surveyor context on a :class:`SurveyorSocket`.

    Surveyor contexts have an independant survey_time parameter as their
    parent socket.
    """
    @property
    def survey_time(self) -> int:
        """
        Survey deadline in milliseconds.

        After sending a survey, the socket accepts responses for this long.
        Once the deadline expires, :meth:`recv` raises :exc:`NngError` with
        ``NngTimeout``.  The next :meth:`send` starts a fresh survey.

        Contexts inherit from the socket parameter at creation.
        """
        ...
    @survey_time.setter
    def survey_time(self, value: int) -> None: ...


class Socket:
    """
    Base class for all nng protocol sockets.

    **Connections and pipes**

    A socket does not correspond to a single connection.  Instead it owns a
    *pool of pipes*, where each pipe is one physical connection:

    * Call :meth:`add_dialer` one or more times to add outbound connections.
      Each call creates and stores a :class:`Dialer`; call
      :meth:`Dialer.start` on it to initiate the connection.  A dialer
      manages one pipe and reconnects automatically if the connection drops.
    * Call :meth:`add_listener` one or more times to accept inbound
      connections.  A single :class:`Listener` can accept unlimited
      simultaneous peers; call :meth:`Listener.start` on it to begin
      accepting.
    * Both can be combined freely on the same socket.
    * The socket keeps strong references to all dialers and listeners it
      creates, so they are not garbage-collected while the socket is open.

    **How messages are routed across pipes**

    This is entirely determined by the protocol subclass:

    * :class:`PubSocket` — broadcast to *all* pipes.
    * :class:`PushSocket` — round-robin / load-balance across pipes.
    * :class:`ReqSocket` — send to *one* available pipe; reply must arrive on
      the same pipe.  Uses the first ready pipe, not strict round-robin.
    * :class:`PairSocket` — one active pipe at a time
    * :class:`BusSocket` — send to *all other* peers.
    * :class:`SurveyorSocket` — broadcast survey; collect all responses.

    ** Thread-safety and concurrency **
    All socket methods are thread-safe and can be called concurrently from
    multiple threads.
    `submit_send`, `submit_recv`, `asend`, and `arecv` internally submit an
    asynchronous operation to the socket's I/O thread and return a Future,
    avoiding to block until completion. They can be called concurrently
    with each other and with `recv`/`send`, as well as from different
    threads or asyncio loops.

    **Available transports**

    The URL scheme passed to :meth:`add_dialer` / :meth:`add_listener` selects
    the transport:

    * **TCP** – ``tcp://<host>:<port>``

      Cross-machine communication over TCP/IP.  Use ``tcp4://`` or ``tcp6://``
      to force IPv4 or IPv6.  When listening, omit the host or use ``0.0.0.0``
      / ``::`` to accept on all interfaces, e.g. ``tcp://0.0.0.0:5555`` or
      simply ``tcp://:5555``.  IPv6 literals must be bracketed:
      ``tcp://[::1]:5555``.

    * **IPC** – ``ipc://<path>``

      Inter-process communication on the same host.  Uses UNIX domain sockets
      on POSIX and named pipes on Windows.  On POSIX, prefer absolute paths to
      avoid working-directory sensitivity.  ``unix://`` is an alias for
      ``ipc://`` on POSIX systems.

    * **Abstract** (Linux only) – ``abstract://<name>``

      Linux abstract-namespace sockets.  Names are URI-encoded and do not
      appear in the filesystem; they are freed automatically when no longer in
      use.  Embedded NUL bytes can be encoded as ``%00``, e.g.
      ``abstract://foo%00bar``.

    * **In-process** – ``inproc://<name>``

      Zero-copy communication between sockets **within the same process**.
      The name is an arbitrary string; different names are completely
      independent. Sockets in separate processes, or using different NNG
      library instances, cannot communicate via inproc.

    * **UDP** *(experimental)* – ``udp://<host>:<port>``

      Unreliable, connectionless transport.  Messages are ordered by nng but
      gaps are possible; there is no delivery guarantee.  Maximum message size
      is effectively ~1140 bytes on standard Ethernet (65 000 B hard cap).
      Use ``udp4://`` or ``udp6://`` to restrict to a specific IP version.
      IPv6 literals must be bracketed: ``udp://[::1]:5555``.

    **Closing**

    Closing a socket (via :meth:`close` or exiting a ``with`` block) waits for
    outstanding operations to finish or be aborted.  All associated dialers,
    listeners, pipes, and contexts are invalidated.

    **Typical usage**::

        with ReqSocket() as sock:
            sock.add_dialer("tcp://127.0.0.1:5555").start()
            sock.send(b"ping")
            reply = sock.recv()
    """
    @property
    def id(self) -> int:
        """The underlying nng socket ID (positive) or 0 if closed."""
        ...

    @property
    def peer_name(self) -> str:
        """Peer protocol name."""
        ...

    @property
    def pipes(self) -> list[Pipe]:
        """
        Snapshot list of currently live :class:`Pipe` objects.

        The list is a copy; it will not change as connections are added or
        removed.  Inspect :attr:`Pipe.status` for the state of each pipe.
        """
        ...

    @property
    def proto_name(self) -> str:
        """Protocol name (e.g. ``"pair1"``)."""
        ...

    @property
    def recv_fd(self) -> int:
        """
        Readable file descriptor for external poll / epoll / kqueue.

        Becomes readable when the socket has data to receive.
        Never read or write to this fd directly.
        """
        ...

    @property
    def recv_timeout(self) -> int:
        """
        Receive timeout in ms (-1 = infinite, 0 = non-blocking).

        This affects all `recv`/`arecv`/`submit_recv` operations on this socket, regardless of pipe,
        starting from the time this option is modified.

        Contexts inherit from this parameter at creation.
        """
        ...
    @recv_timeout.setter
    def recv_timeout(self, value: int) -> None: ...

    @property
    def send_fd(self) -> int:
        """
        Writable file descriptor for external poll / epoll / kqueue.

        Becomes writable when the socket can accept a send.
        """
        ...

    @property
    def send_timeout(self) -> int:
        """
        Send timeout in ms (-1 = infinite, 0 = non-blocking).

        This affects all `send`/`asend`/`submit_send` operations on this socket, regardless of pipe,
        starting from the time this option is modified.

        Contexts inherit from this parameter at creation.
        """
        ...
    @send_timeout.setter
    def send_timeout(self, value: int) -> None: ...

    def add_dialer(self, url: str | bytes, *, tls: TlsConfig | None = None, reconnect_min_ms: int | None = None, reconnect_max_ms: int | None = None, recv_max_size: Any = None, tcp_nodelay: bool | None = None, tcp_keepalive: bool | None = None, tcp_local_addr: str | None = None) -> Dialer:
        """
        Create, configure, and register an outbound :class:`Dialer` for *url*.

        The dialer is created and all options applied, but the connection is
        **not** started yet.  Call :meth:`Dialer.start` on the returned object
        to initiate the connection::

            dialer = sock.add_dialer("tcp://127.0.0.1:5555",
                                     reconnect_min_ms=100)
            dialer.start()          # blocks until first connection succeeds

            # or as a one-liner:
            sock.add_dialer("tcp://127.0.0.1:5555").start()

        The socket keeps a strong reference to the returned :class:`Dialer`;
        it will not be garbage-collected while the socket is open.

        Each call registers **one** outbound connection slot.  Call
        :meth:`add_dialer` multiple times to connect to several peers; the
        protocol layer pools all resulting pipes and distributes messages
        across them.

        Note the self address of a dialer after it has connected to a peer
        can be retrieved from the dialer's active pipe (``dialer.pipe.get_self_addr()``),
        and may change at every reconnection (in particular the port).

        Parameters
        ----------
        url:
            Connection URL.  Supported schemes:

            * ``tcp://host:port`` — TCP/IP.  *host* is a DNS name or an
              IPv4/IPv6 address literal.  IPv6 addresses must be bracketed:
              ``tcp://[::1]:5555``.  Use ``tcp4://`` or ``tcp6://`` to force
              IPv4-only or IPv6-only DNS resolution respectively.  The port
              is required and must be non-zero (you are connecting *to* a
              port, not binding one).
            * ``ipc:///path/to/socket`` — Unix-domain socket (POSIX only).
            * ``inproc://name`` — in-process transport (same process only).
            * ``ws://host:port/path`` — WebSocket.
            * ``wss://host:port/path`` — WebSocket over TLS.
        tls:
            A :class:`TlsConfig` for TLS connections.
        reconnect_min_ms:
            Minimum reconnect interval in ms (default: 100).  After a
            disconnect the dialer waits at least this long before retrying.
        reconnect_max_ms:
            Maximum reconnect interval in ms.  Retries use exponential
            back-off capped at this value.  ``0`` (default) means use
            *reconnect_min_ms* as a fixed interval.
        recv_max_size:
            Maximum incoming message size in bytes (Default: 0 = no limit).
            Messages beyond the limit will be discarded. Use this to
            protect against misbehaving peers sending huge messages.
        tcp_nodelay:
            Set ``NNG_OPT_TCP_NODELAY`` on the TCP connection.  ``True``
            disables Nagle's algorithm (lower latency, potentially more
            packets).  ``False`` enables it (fewer, larger packets).
            ``None`` (default) leaves the OS/nng default in place (True).
            Has no effect for non-TCP transports.
        tcp_keepalive:
            Set ``NNG_OPT_TCP_KEEPALIVE`` on the TCP connection.  ``True``
            enables TCP keep-alive probes, which detect dead connections even
            when no application data is flowing.  ``None`` (default) leaves
            the OS/nng default in place (False).  Has no effect for non-TCP transports.
        tcp_local_addr:
            Source IP address string (e.g. ``"192.168.1.5"`` or ``"::1"``)
            to bind the outgoing connection to. Only useful on multi-homed hosts
            to select a specific network interface.  The port is ignored —
            the OS assigns an ephemeral source port automatically.  ``None``
            (default) lets the OS choose the source address.  Only supported
            for TCP (``tcp://`` scheme).

        Raises
        ------
        NngClosed
            If the socket has been closed.
        NngNotSupported
            If *url* uses a transport scheme that is not recognized by nng
            (e.g. ``"unknown://host:1234"``).  Note: nng raises NngNotSupported
            rather than NngInvalidArgument for unrecognized transport names.
        NngInvalidArgument
            If *url* is otherwise syntactically invalid for a known transport.
        ValueError
            If *tcp_local_addr* is not a valid IPv4 or IPv6 address string.
        """
        ...

    def add_listener(self, url: str | bytes, *, tls: TlsConfig | None = None, recv_max_size: Any = None, tcp_nodelay: bool | None = None, tcp_keepalive: bool | None = None) -> Listener:
        """
        Create, configure, and register an inbound :class:`Listener` for *url*.

        The listener is created and all options applied, but it does **not**
        start accepting connections yet.  Call :meth:`Listener.start` on the
        returned object to begin listening::

            lst = sock.add_listener("tcp://0.0.0.0:5555")
            lst.start()

            # or as a one-liner:
            sock.add_listener("tcp://0.0.0.0:5555").start()

        The socket keeps a strong reference to the returned :class:`Listener`;
        it will not be garbage-collected while the socket is open.

        A listener accepts **unlimited** simultaneous inbound connections, each
        of which becomes a pipe in the socket's pool.  Call
        :meth:`add_listener` multiple times to accept on several addresses or
        transports at once.

        Parameters
        ----------
        url:
            Address to bind to.  Supported schemes:

            * ``tcp://host:port`` — TCP/IP.  Use ``0.0.0.0`` (or simply ``:``)
              to accept on all local IPv4 interfaces, ``[::]`` for all local
              IPv6 interfaces, or an explicit IP to restrict to a single interface
              (e.g. ``tcp://127.0.0.1:5555`` for loopback-only).  Use ``tcp4://``
              or ``tcp6://`` to force a specific IP version.  Port ``0`` lets
              the OS assign an ephemeral port; retrieve the actual port from
              :attr:`Listener.port` after :meth:`Listener.start` returns.
            * ``ipc:///path/to/socket`` — Unix-domain socket or Windows named pipe.
            * ``inproc://name`` — in-process transport (same process only).
            * ``ws://addr:port/path`` — WebSocket.
            * ``wss://addr:port/path`` — WebSocket over TLS.
        tls:
            A :class:`TlsConfig` for TLS connections.
        recv_max_size:
            Maximum incoming message size in bytes (Default: 0 = no limit).
            Messages beyond the limit will be discarded. Use this to
            protect against misbehaving peers sending huge messages.
        tcp_nodelay:
            Set ``NNG_OPT_TCP_NODELAY`` on accepted TCP connections.  ``True``
            disables Nagle's algorithm (lower latency, potentially more
            packets).  ``None`` (default) leaves the OS/nng default in place (True).
            Has no effect for non-TCP transports.
        tcp_keepalive:
            Set ``NNG_OPT_TCP_KEEPALIVE`` on accepted TCP connections.  ``True``
            enables TCP keep-alive probes.  ``None`` (default) leaves the
            OS/nng default in place (False).  Has no effect for non-TCP transports.

        Raises
        ------
        NngClosed
            If the socket has been closed.
        NngNotSupported
            If *url* uses a transport scheme that is not recognized by nng
            (e.g. ``"unknown://host:1234"``).  Note: nng raises NngNotSupported
            rather than NngInvalidArgument for unrecognized transport names.
        NngInvalidArgument
            If *url* is otherwise syntactically invalid for a known transport.
        NngAddressInUse
            If the address is already bound by another listener.
        """
        ...

    async def arecv(self) -> Message:
        """Receive bytes asynchronously (asyncio-compatible)."""
        ...

    def arecv_ready(self) -> AsyncGenerator[None, None]:
        """
        Async generator that yields each time the socket has a message ready.

        ``recv_fd`` is registered with the event loop *once* for the lifetime of
        the generator — ``add_reader`` / ``remove_reader`` are each called only
        once regardless of how many messages are awaited.  Epoll fires directly
        in the event loop thread with no nng thread pool and no
        ``call_soon_threadsafe`` round-trip.

        After each ``yield``, a call to :meth:`recv` / :meth:`recv_msg` with
        ``nonblock=True`` is guaranteed to succeed immediately::

            watcher = sock.arecv_ready()
            async for _ in watcher:
                data = sock.recv(nonblock=True)
                # or equivalently:
                # await watcher.__anext__()
                # data = sock.recv(nonblock=True)
            await watcher.aclose()
        """
        ...

    async def asend(self, data: bytes | Message | Buffer | bytearray | str) -> None:
        """
        Send bytes asynchronously (asyncio-compatible).

        NOTE: if the coroutine is cancelled while waiting for send
        completion, the data may or may not have been sent.
        """
        ...

    def asend_ready(self) -> AsyncGenerator[None, None]:
        """
        Async generator that yields each time the socket can accept a send.

        ``send_fd`` is registered with the event loop *once* for the lifetime of
        the generator — ``add_reader`` / ``remove_reader`` are each called only
        once regardless of how many sends are awaited.  Epoll fires directly in
        the event loop thread with no nng thread pool and no
        ``call_soon_threadsafe`` round-trip.

        After each ``yield``, a call to :meth:`send` / :meth:`send_msg` with
        ``nonblock=True`` is guaranteed to succeed immediately.

        For REP sockets the fd becomes readable as soon as nng has finished
        sending the previous reply — making this the ideal low-latency
        synchronisation point before a non-blocking send::

            recv_watcher = sock.arecv_ready()
            send_watcher = sock.asend_ready()
            async for _ in recv_watcher:
                msg = sock.recv(nonblock=True)
                await send_watcher.__anext__()
                sock.send(reply, nonblock=True)
            await send_watcher.aclose()
        """
        ...

    def close(self) -> None:
        """
        Close the socket and release all resources.

        Waits for any outstanding operations to complete or be aborted before
        returning.  All associated :class:`Dialer`, :class:`Listener`,
        :class:`Pipe`, and :class:`Context` objects are invalidated.

        .. note::
            This method blocks until in-flight operations finish.  Do not call
            it from a context that cannot block.  Closing the socket may
            disrupt transfers that are still in progress.
        """
        ...

    @property
    def on_new_pipe(self) -> Callable[[Pipe], None] | None:
        """
        Callback invoked when a new connection is negotiated.

        The callback is called at :attr:`PipeStatus.ADDING` – before the pipe
        is admitted to the socket pool.  Calling :meth:`Pipe.close` inside
        the callback rejects the connection entirely.

        Only one callback is kept; assigning again replaces the previous one.
        Set to ``None`` to disable.

        The callback signature is ``(pipe: Pipe) -> None``.  It is executed on
        the dispatcher thread; keep it short and non-blocking.
        """
        ...
    @on_new_pipe.setter
    def on_new_pipe(self, value: Callable[[Pipe], None] | None) -> None: ...

    def recv(self, *, nonblock: bool = False) -> Message:
        """
        Receive and return a :class:`Message` (zero-copy via buffer protocol).

        Parameters
        ----------
        nonblock:
            If *True*, raise :exc:`NngAgain` if no message is ready.
        """
        ...

    def send(self, data: bytes | Message | Buffer | bytearray | str, *, nonblock: bool = False) -> None:
        """
        Send an :class:`Message`.  Transfers ownership on success.

        Parameters
        ----------
        data:
            The :class:`Message` (or bytes-like) to send.
        nonblock:
            If *True*, raise :exc:`NngAgain` instead of blocking.
        """
        ...

    def submit_recv(self) -> concurrent.futures.Future[Message]:
        """
        Receive asynchronously; return a concurrent.futures.Future → bytes.

        The future resolves to the received payload as ``bytes``.
        Can be called from any thread.
        """
        ...

    def submit_send(self, data: bytes | Message | Buffer | bytearray | str) -> concurrent.futures.Future[None]:
        """
        Send *data* (bytes-like) asynchronously; return a concurrent.futures.Future.

        The future resolves to ``None`` on success or raises an :exc:`NngError`
        on failure. Can be called from any thread.
        """
        ...

    def __enter__(self) -> Self:
        ...

    def __exit__(self, *_: Any) -> None:
        ...

    def __repr__(self) -> str:
        """Return repr(self)."""
        ...


class PairSocket(Socket):
    """
    Bidirectional, point-to-point socket (Pair protocol).

    A pair socket can send and receive freely in both directions.  In standard
    mode it is strictly **one-to-one**: only a single pipe is active at a time.
    Messages sent while no pipe is connected are held in the send buffer.

    .. note::
       PAIR does **not** guarantee reliable delivery.  Although back-pressure
       prevents most discards, some topologies can still lose messages.
       Applications that need reliable delivery should use :class:`ReqSocket`
       or add their own acknowledgment layer.

    **Protocol versions**

    The default is Pair v1.  Pass ``v0=True`` for the legacy v0 protocol, which
    lacks hop-count headers and is required when interoperating with older
    implementations such as *libnanomsg* or *mangos*.

    Parameters
    ----------
    v0:
        Use the older Pair v0 protocol instead of the default v1.
    """
    @property
    def recv_buf(self) -> int:
        """
        Receive buffer depth (number of queued messages) before blocking.

        The Pair protocol blocks sending messages on the other side until
        the message can be received successfully into the queue.

        A value of 0 (the default) means no buffering, i.e. any unqueued send
        on the other side is blocked until this side does a receive operation.

        This value must be an integer between 0 and 8192, inclusive.
        """
        ...
    @recv_buf.setter
    def recv_buf(self, value: int) -> None: ...

    @property
    def send_buf(self) -> int:
        """
        Send buffer depth (number of queued messages) before blocking.

        When non zero, messages are queues to a send buffer until the
        recepient side can receive them.  When the buffer is full, the sender blocks
        until space is available. 0 means no buffering, i.e. the sender blocks until
        the message can be received.

        The default for Pair is 0.

        This value must be an integer between 0 and 8192, inclusive.
        """
        ...
    @send_buf.setter
    def send_buf(self, value: int) -> None: ...


class PubSocket(Socket):
    """
    Publish socket — broadcasts every message to **all** connected subscribers.

    A message sent on a ``PubSocket`` is delivered to every :class:`SubSocket`
    peer that has a matching subscription prefix.  Peers with no matching
    subscription silently discard the message.

    * **Fan-out**: one send → copied to all active pipes.
    * **Topic filtering**: filtering happens on the *subscriber* side based on the
      message body prefix (see :meth:`SubSocket.subscribe`).  The publisher
      always sends every message to every subscriber; subscriptions do **not**
      reduce network bandwidth.
    * **No back-pressure**: a slow subscriber does not block the publisher;
      messages for that subscriber are dropped when its send buffer is full.
    * PubSocket cannot receive; :meth:`recv` raises ``NngNotSupported``.
    """
    @property
    def send_buf(self) -> int:
        """
        Send buffer depth (number of queued messages) before dropping messages.

        The send queue enables to queue messages, enabling recipients time to
        receive all of them. When the buffer is full, older messages are dropped and
        cannot be received anymore by the subscribers.
        The default is 16 for Pub.

        This value must be an integer between 0 and 8192, inclusive.
        """
        ...
    @send_buf.setter
    def send_buf(self, value: int) -> None: ...


class SubSocket(Socket):
    """
    Subscribe socket — receives messages from a :class:`PubSocket`.

    By default a ``SubSocket`` receives **nothing**.  You must subscribe to at
    least one topic prefix with :meth:`subscribe` before any messages arrive.
    The socket can hold multiple subscriptions simultaneously.

    Messages whose body does *not* start with at least one registered prefix
    are silently dropped by nng before they reach the application.  Topic
    filtering is done **locally** on the subscriber side — the publisher always
    sends every message to every subscriber, so subscriptions do not reduce
    bandwidth consumption.

    * SubSocket is receive-only; :meth:`send` raises ``NngNotSupported``.
    * One ``SubSocket`` can connect to multiple publishers by calling
      :meth:`add_dialer` several times.
    * When the receive queue is full, **newer** messages are kept and older
      unread messages are discarded by default.

    Example::

        sub = SubSocket()
        sub.add_dialer("tcp://127.0.0.1:5556").start()
        sub.subscribe(b"")       # receive every message
        sub.subscribe(b"news.")  # also accept prefix-matched topics
        msg = sub.recv()
    """
    @property
    def recv_buf(self) -> int:
        """
        Receive buffer depth (number of queued messages) before dropping messages.

        If the buffer is full, new messages are dropped according to
        the skip_older_on_full_queue policy.

        The default value is 128.

        This value must be an integer between 0 and 8192, inclusive.
        """
        ...
    @recv_buf.setter
    def recv_buf(self, value: int) -> None: ...

    @property
    def skip_older_on_full_queue(self) -> bool:
        """
        Whether to drop older messages when the receive queue is full.

        By default, when the receive queue is full, newer messages are kept and
        older unread messages are dropped.  Setting this option to ``False``
        reverses that behavior: older messages are kept and newer messages are
        dropped instead.
        """
        ...
    @skip_older_on_full_queue.setter
    def skip_older_on_full_queue(self, value: bool) -> None: ...

    def open_context(self) -> SubContext:
        """Open an independent sub context on this socket."""
        ...

    def subscribe(self, prefix: bytes = b'') -> None:
        """
        Subscribe to messages whose body starts with *prefix*.

        An empty prefix subscribes to all messages.
        """
        ...

    def unsubscribe(self, prefix: bytes = b'') -> None:
        """Remove a topic subscription."""
        ...


class ReqSocket(Socket):
    """
    Request socket — sends a request and waits for exactly one reply.

    The REQ/REP protocol enforces a strict send → receive → send → … cycle on
    each context.  Violating this order (e.g. two sends in a row) raises an
    error.

    **Message routing with multiple peers**

    When the socket has several pipes (e.g. after multiple :meth:`add_dialer`
    calls or when connected to a server with multiple workers via contexts),
    each request is sent to the **first available** pipe — whichever peer is
    ready to accept it.  The reply is expected to arrive on the *same* pipe.

    If the pipe dies before the reply arrives, the request is automatically
    resent on another available pipe (see :attr:`resend_time`).  Because
    requests may be retransmitted, they should be **idempotent** — executing
    the same request twice must produce the same result.  If that is not
    possible, set :attr:`resend_time` to ``-1`` to disable automatic resending.

    Cancelling a pending request is done by sending a new request; any reply
    from the cancelled request that arrives later is silently discarded.

    **Concurrent requests**

    A bare ``ReqSocket`` allows only one in-flight request at a time.  To
    issue multiple concurrent requests, open independent contexts with
    :meth:`open_context`.  Each context runs its own REQ state machine and can
    be in-flight on a different pipe simultaneously.
    """
    @property
    def resend_tick(self) -> int:
        """
        How often (ms) to check for timed-out requests to resend.

        The socket checks for timed-out requests at this interval.
        Lower values add overhead, but are needed for short resend_time values.

        The default is 1000 ms.
        """
        ...
    @resend_tick.setter
    def resend_tick(self, value: int) -> None: ...

    @property
    def resend_time(self) -> int:
        """
        How long (ms) to wait for a reply before resending the request.

        Requests are automatically resent if the peer disconnects.

        resend_time adds a timer at which requests will be resent (even if no
        disconnection has been detected) to the peer until a reply is received.

        ``-1`` (the default) disables automatic resending (exception on disconnect)
        Setting a positive value provides automatic fault-tolerance when working with
        multiple REP peers, or possible packet loss. However it has the drawback
        of causing a pipe connection loss upon receiving a reply of the previous
        request after the resend timer has fired.

        Setting a < 1000ms resend_time requires tuning :attr:`resend_tick` to
        have real effect.
        """
        ...
    @resend_time.setter
    def resend_time(self, value: int) -> None: ...

    def open_context(self) -> ReqContext:
        """
        Open an independent REQ context on this socket.

        Each context has its own send → receive → send state machine and can
        have a request in-flight on a different pipe at the same time as other
        contexts.  This is the preferred way to pipeline concurrent requests
        without opening multiple sockets.
        """
        ...


class RepSocket(Socket):
    """
    Reply socket — receives a request and sends exactly one reply.

    The REP/REQ protocol enforces a strict receive → send → receive → … cycle
    on each context.  Attempting to send a reply before receiving a request, or
    to receive a second request before replying to the first, raises
    ``NngState``.

    **Serving multiple concurrent clients**

    A single ``RepSocket`` can be connected to any number of request senders
    (via :meth:`add_listener` or :meth:`add_dialer`).  However, the
    socket-level :meth:`recv` / :meth:`send` cycle handles only **one request
    at a time** — only one receive operation may be pending simultaneously.
    To serve multiple clients concurrently without blocking, open independent
    per-client contexts with :meth:`open_context`; each context carries the
    reply-routing state for one in-flight request.
    """
    def open_context(self) -> Context:
        """
        Open an independent REP context on this socket.

        Each context can receive one request and send one reply independently
        of all other contexts.  Use this to serve multiple clients concurrently
        from a single socket without a thread per client.
        """
        ...


class PushSocket(Socket):
    """
    Push socket — distributes messages across connected pull peers (pipeline).

    PUSH/PULL implements a fan-out work queue.  Each message sent on a
    ``PushSocket`` is delivered to **exactly one** :class:`PullSocket` peer,
    chosen by a fair round-robin / load-balancing algorithm that favours peers
    with available buffer space.

    * Messages are never duplicated — each goes to one worker.
    * If there are no connected peers the send blocks (or raises
      :exc:`NngAgain` in non-blocking mode) until a peer is available.  Back-
      pressure is honoured: only peers capable of accepting a message are
      considered.
    * PushSocket is send-only; :meth:`recv` raises ``NngNotSupported``.
    * **No delivery guarantee**: there is no acknowledgment mechanism.  If
      reliable delivery is required, consider :class:`ReqSocket` instead.
    """
    @property
    def send_buf(self) -> int:
        """
        Send buffer depth (number of queued messages) before blocking.

        When non zero, messages are queues to a send buffer until the
        recepient side can receive them.  When the buffer is full, the sender blocks
        until space is available.

        Default (0), means operations are unbuffers, and sending will block
        until a peer is available to receive the message.

        The default for Push is 0.

        This value must be an integer between 0 and 8192, inclusive.
        """
        ...
    @send_buf.setter
    def send_buf(self, value: int) -> None: ...


class PullSocket(Socket):
    """
    Pull socket — receives work items distributed by a :class:`PushSocket`.

    Each message arrives from exactly one push sender and is delivered to
    exactly this socket (not duplicated to others).  Multiple ``PullSocket``
    instances connected to the same ``PushSocket`` act as a pool of workers:
    nng load-balances across them automatically.

    When two peers both have a message ready simultaneously, the order in which
    messages are delivered to the application is undefined.

    * PullSocket is receive-only; :meth:`send` raises ``NngNotSupported``.
    """
    ...

class SurveyorSocket(Socket):
    """
    Surveyor socket — broadcasts a survey and collects responses within a deadline.

    Sending a message broadcasts it to **all** connected
    :class:`RespondentSocket` peers.  Respondents are not obliged to reply;
    the surveyor collects as many responses as arrive within :attr:`survey_time`
    milliseconds.  After the deadline expires, further :meth:`recv` calls raise
    :exc:`NngError` with ``NngTimeout`` and :meth:`recv` before any survey
    has been sent raises ``NngState``.

    Sending a new survey **cancels** the previous one; any responses from the
    earlier survey that arrive afterwards are silently discarded.

    Each connected respondent normally sends at most one reply per survey,
    though duplicates are possible in some topologies.

    Useful for solving voting / leader-election and service-discovery problems.

    Each send opens a new survey; the previous survey's results are discarded.
    Use :meth:`open_context` to run multiple independent surveys concurrently;
    each context maintains its own deadline and does not cancel surveys on
    other contexts.
    """
    @property
    def survey_time(self) -> int:
        """
        Survey deadline in milliseconds.

        After sending a survey, the socket accepts responses for this long.
        Once the deadline expires, :meth:`recv` raises :exc:`NngError` with
        ``NngTimeout``.  The next :meth:`send` starts a fresh survey.
        """
        ...
    @survey_time.setter
    def survey_time(self, value: int) -> None: ...

    def open_context(self) -> SurveyorContext:
        """Open an independent surveyor context on this socket."""
        ...


class RespondentSocket(Socket):
    """
    Respondent socket — receives surveys and sends back a single response each.

    The protocol is similar to REP: :meth:`recv` waits for an incoming survey,
    and :meth:`send` delivers the response back to the surveyor that sent it.
    Multiple respondents can reply to the same survey; the surveyor collects
    all replies within its deadline.

    A respondent may choose to discard a survey by simply not replying to it.
    Attempting to :meth:`send` without first receiving a survey raises
    ``NngState``.

    Useful for voting / leader-election and service-discovery problems.

    Use :meth:`open_context` to receive and respond to multiple surveys in
    parallel; each context has its own independent state machine.
    """
    def open_context(self) -> Context:
        """Open an independent respondent context on this socket."""
        ...


class BusSocket(Socket):
    """
    Bus socket — broadcasts each message to **all** other connected bus nodes.

    Every message sent on a ``BusSocket`` is forwarded to every other
    ``BusSocket`` peer **directly** connected to it.  Unlike PUB/SUB there is
    no topic filtering and the bus is symmetric: all peers can both send and
    receive.

    Typical use case: all-to-all communication where every node needs to hear
    about events from every other node.

    .. important::
       Messages are only delivered to **directly** connected peers.  Peers
       connected indirectly (e.g. via an intermediate node) will **not**
       receive them.  To achieve true all-to-all communication you must build
       a fully-connected mesh.

    .. note::
       BUS delivery is **best-effort**: sends never block.  If a peer cannot
       receive (e.g. its buffer is full), its copy of the message is silently
       discarded without affecting other peers.  The protocol is not suitable
       for high-throughput workloads where loss would be unacceptable.
    """
    @property
    def recv_buf(self) -> int:
        """
        Receive buffer depth (number of queued messages) before dropping.

        The blocking or dropping behavior depends on the protocol.

        The default is 16 for Bus

        A value of 0 means no buffering. The socket will drop 
        messages unless it is actively listening for them.

        This value must be an integer between 0 and 8192, inclusive.
        """
        ...
    @recv_buf.setter
    def recv_buf(self, value: int) -> None: ...

    @property
    def send_buf(self) -> int:
        """
        Send buffer depth (number of queued messages) before dropping.

        The default is 16 for Bus.

        A value of 0 means no buffering; the socket will drop messages
        unless the receiver is directly ready to receive them.

        This value must be an integer between 0 and 8192, inclusive.
        """
        ...
    @send_buf.setter
    def send_buf(self, value: int) -> None: ...


# ---------------------------------------------------------------------------
# Module-level constants
# ---------------------------------------------------------------------------

# Module-level constants

TLS_AUTH_NONE: int
TLS_AUTH_OPTIONAL: int
TLS_AUTH_REQUIRED: int
TLS_VERSION_1_2: int
TLS_VERSION_1_3: int

# ---------------------------------------------------------------------------
# Module-level functions
# ---------------------------------------------------------------------------

# Module-level functions

def version() -> Any:
    """Return the nng library version string (e.g. ``"2.0.0-dev"``)."""
    ...

def random() -> Any:
    """Return a 32-bit cryptographically random value."""
    ...

def initialize(*, num_task_threads: int = 0, max_task_threads: int = -1, num_expire_threads: int = 0, max_expire_threads: int = -1, num_poller_threads: int = 0, max_poller_threads: int = -1, num_resolver_threads: int = 0) -> Any:
    """
    Initialise the nng library with custom threading parameters.

    Must be called **before** creating any nng object or calling any nng
    function.  If not called explicitly, the library is auto-initialised with
    default parameters on first use.

    Parameters (all keyword-only, default 0 / -1 = nng default / no cap):
        num_task_threads     – fixed number of task-queue threads (0 = auto)
        max_task_threads     – cap on task-queue threads (-1 = no cap)
        num_expire_threads   – fixed number of expiry threads (0 = auto)
        max_expire_threads   – cap on expiry threads (-1 = no cap)
        num_poller_threads   – fixed number of I/O poller threads (0 = auto)
        max_poller_threads   – cap on poller threads (-1 = no cap)
        num_resolver_threads – fixed number of DNS resolver threads (0 = auto)

    Raises RuntimeError if nng is already initialised or if nng_init() fails.
    """
    ...

def tls_engine_name() -> Any:
    """
    Return the short name of the currently loaded TLS engine.

    Returns ``'none'`` when no TLS engine has been registered (i.e.
    the library was built without TLS support).

    Returns:
        A short identifier string, e.g. ``'mbed'``, ``'openssl'``, or
        ``'wolf'``.
    """
    ...

def tls_engine_description() -> Any:
    """
    Return a human-readable description of the currently loaded TLS engine.

    Returns an empty string when no TLS engine has been registered.

    Returns:
        A free-form description string, e.g. ``'mbedTLS 3.6.2'``.
    """
    ...
